# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-17 15:25
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
