# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-17 17:16
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_live_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='landing_page',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
